# nginx proxy address - http://172.17.0.1:8000

name: plausible
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: plausible/analytics:latest
    container_name: plausible-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:8000:8000'
    volumes:
      - './volumes/data/plausible:/data'
    networks:
      - plausible

networks:
  plausible:
    name: plausible
    external: false
